[profile.default]
optimizer = true
optimizer_runs = 200
src = "src"
out = "out"
libs = ["lib"]
fs_permissions = [{ access = "read-write", path = "./"}]
gas_reports = ["*"]
# Enable CBOR metadata for better verification compatibility
cbor_metadata = true

[rpc_endpoints]
1 = "https://mainnet.gateway.tenderly.co"
mainnet = "https://mainnet.gateway.tenderly.co"
11155111 = "https://sepolia.gateway.tenderly.co"
sepolia = "https://sepolia.gateway.tenderly.co"

560048 = "https://ethereum-hoodi-rpc.publicnode.com"
hoodi = "https://ethereum-hoodi-rpc.publicnode.com"

[etherscan]
sepolia = { key = "${ETHERSCAN_API_KEY}", url = "https://api-sepolia.etherscan.io/api", chain = 11155111 }
hoodi = { key = "${ETHERSCAN_API_KEY}", url = "https://api-hoodi.etherscan.io/api", chain = 560048 }
mainnet = { key = "${ETHERSCAN_API_KEY}", url = "https://api.etherscan.io/api", chain = 1 }

[fmt]
bracket_spacing = false
int_types = "long"
line_length = 120
multiline_func_header = "attributes_first"
number_underscore = "thousands"
quote_style = "double"
tab_width = 4