[profile.default]
optimizer = true
optimizer_runs = 200
src = "src"
out = "out"
libs = ["lib"]
fs_permissions = [{ access = "read-write", path = "./"}]
gas_reports = ["*"]

[rpc_endpoints]
11155111 = "https://gateway.tenderly.co/public/sepolia"
sepolia = "https://gateway.tenderly.co/public/sepolia"

560048 = "https://ethereum-hoodi-rpc.publicnode.com"
hoodi = "https://ethereum-hoodi-rpc.publicnode.com"

[etherscan]
sepolia = { key = "${ETHERSCAN_API_KEY}", url = "https://api-sepolia.etherscan.io/api", chain = 11155111 }
hoodi = { key = "${ETHERSCAN_API_KEY}", url = "https://api-hoodi.etherscan.io/api", chain = 560048 }

[fmt]
bracket_spacing = false
int_types = "long"
line_length = 120
multiline_func_header = "attributes_first"
number_underscore = "thousands"
quote_style = "double"
tab_width = 4
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options